from logging import INFO

import numpy as np

from AI.src.stuffMerger.enums import MotionType
from AI.src.stuffMerger.utils.image_processing_utility import *
from AI.src.stuffMerger.utils.pen_calibration import SwipeCalibrator
from AI.src.stuffMerger.utils.resources_utility import *

from AI.src.constants import  *


class OldMotionModule:
    """
    image_mask: PIL Image used as mask for the movement, should be RGBA with transparency where the map is to be ignored,
        ignored zones are feasible for movement.
    starting_positions: (x, y) starting position on the map [default is (0,0), Top left corner]
    screen_size: (width, height) size of the screen
    motion_type: type of motion to use (swipe, tap)
    motion_area: ((left_x,top_y), (right_x,bottom_y)) area of the screen to use for the motion
        [REQUIRED IF motion_type is SWIPE]
    motion_options: ((x,y), (x,y), (x,y), (x,y)) up, right, down, left positions for tap motion
        [REQUIRED IF motion_type is TAP]
    """
    # TODO: another possible motion type is TAP_AND_HOLD where times define how much we move in a specific direction
    # TODO: proper diagonal support
    def __init__(self,
                 image_mask: Image.Image,
                 screen_size: tuple[int, int],
                 starting_positions: tuple[int, int] | None = (0, 0),
                 motion_type: MotionType = MotionType.SWIPE,
                 motion_area: tuple[tuple[int, int], tuple[int, int]] | None = None,
                 motion_options: tuple[tuple[int, int], tuple[int, int], tuple[int, int], tuple[int, int]] | None = None
                 ):
        self.position: tuple[int, int] = starting_positions
        self.position_history: list[tuple[int, int]] = [self.position]
        self.image_mask: Image.Image = image_mask
        self.mask: np.ndarray = np.array(image_mask, dtype=np.int32)
        self.screen_size: tuple[int, int] = screen_size
        self.motion_type: MotionType = motion_type
        self.motion_area: tuple[tuple[int, int], tuple[int, int]] | None = motion_area
        self.motion_options: tuple[tuple[int, int], tuple[int, int], tuple[int, int], tuple[int, int]] | None = motion_options
        if self.motion_type == MotionType.SWIPE and self.motion_area is None:
            raise ValueError("motion_area must be defined when motion_type is SWIPE")
        elif self.motion_type == MotionType.TAP and self.motion_options is None:
            raise ValueError("motion_options must be defined when motion_type is TAP")


    def move(self,
             destination_offset: tuple[int, int],
             step_number: tuple[int, int] = (4, 4),
             check_range: tuple[int, int] = (-30, 30),
             check_frequency: int = 1,
             desk: Image.Image | None = None,
             desk_coordinates: tuple[int, int] | None = None
             ) -> tuple[tuple[int, float], tuple[int, float]]:
        """
        destination_offset: (x, y) define where you want to go relative to the current position
        step_number: how many steps you want to take to get there (steps are done for x an y separately)
            if in TAP mode destination offset will be only used to define the actual position but will not be checked.
        check_range: range of offset to validate the location (a, b) a->b (a can be negative)
        check_frequency: how many pixels between each check (1 = every pixel)
        desk: the desk image generated by the movement, if not passed it will not be generated, if it is it will be overwritten
        desk_coordinates: (x, y) coordinates on the desk where to paste the movement images (referred to the top left
            corner of the screen) is not passed the borders of the desk will be used
        return: ((x_offset, x_error), (y_offset, y_error))
            if in TAP mode the error will be 0 since no checking is done
        """
        #TODO: implement motion types
        if check_range[0] > check_range[1]:
            raise ValueError("check_range[0] must be lower than check_range[1]")

        x_offsets: list[int] = []
        x_scores: list[float] = []
        if destination_offset[0] != 0:
            x_steps = [destination_offset[0] // step_number[0] for _ in range(step_number[0])]
            x_orientation = Orientation.DESCENDING if destination_offset[0] > 0 else Orientation.ASCENDING  # Forse ho invertito descending e ascending
            if sum(x_steps) != destination_offset[0]:
                x_steps[-1] += destination_offset[0] - sum(x_steps)
            x_images: list[Image.Image] = [get_image().convert("RGBA")]

            for i in range(step_number[0]):
                #TODO: if we're not in the correct position we should recalculate the steps to try and get to the correct end position
                next_img = get_custom_image(
                    orientation=x_orientation,
                    direction=Direction.HORIZONTAL,
                    offset=x_steps[i],
                    name=f"x_{i}.png"
                ).convert("RGBA")
                best_shift, best_score = find_best_offset(
                    _img0=x_images[-1],
                    _img1=next_img,
                    _mask=self.mask,
                    base_shift=x_steps[i],
                    check_range=(check_range[0], check_range[1]),
                    check_step=check_frequency,
                    direction=Direction.HORIZONTAL,  # più che direction sarebbe verso
                    orientation=x_orientation
                )
                delta = best_shift + (-x_steps[i] if x_orientation == Orientation.DESCENDING else x_steps[i])
                logger.log(INFO, f"Best horizontal shift: {best_shift} px (delta vs STEP: {delta} px), score: {best_score:.4f}")
                x_offsets.append(best_shift)
                x_scores.append(best_score)
                self.position = (self.position[0] + best_shift, self.position[1])
                self.position_history.append(self.position)
                x_images.append(next_img)

        y_offsets: list[int] = []
        y_scores: list[float] = []
        if destination_offset[1] != 0:
            y_steps = [destination_offset[1] // step_number[1] for _ in range(step_number[1])]
            y_orientation = Orientation.DESCENDING if destination_offset[
                                                          1] > 0 else Orientation.ASCENDING  # Forse ho invertito descending e ascending
            if sum(y_steps) != destination_offset[1]:
                y_steps[-1] += destination_offset[1] - sum(y_steps)
            y_images: list[Image.Image] = [get_image().convert("RGBA")]

            for i in range(step_number[1]):
                next_img = get_custom_image(
                    orientation=y_orientation,
                    direction=Direction.VERTICAL,
                    offset=y_steps[i],
                    name=f"y_{i}.png"
                ).convert("RGBA")
                best_shift, best_score = find_best_offset(
                    _img0=y_images[-1],
                    _img1=next_img,
                    _mask=self.mask,
                    base_shift=y_steps[i],
                    check_range=(check_range[0], check_range[1]),
                    check_step=check_frequency,
                    direction=Direction.VERTICAL,  # più che direction sarebbe verso
                    orientation=y_orientation
                )
                delta = best_shift + (-y_steps[i] if y_orientation == Orientation.DESCENDING else y_steps[i])
                logger.log(INFO,
                           f"Best vertical shift: {best_shift} px (delta vs STEP: {delta} px), score: {best_score:.4f}")
                y_offsets.append(best_shift)
                y_scores.append(best_score)
                self.position = (self.position[0], self.position[1] + best_shift)
                self.position_history.append(self.position)
                y_images.append(next_img)

        # End Phase

        if desk is not None:
            try:
                shift_x = 0 if x_orientation == Orientation.DESCENDING \
                            else (desk.width - x_images[0].width - sum(x_steps) // len(x_steps))
            except:
                shift_x = 0

            try:
                shift_y = 0 if y_orientation == Orientation.DESCENDING \
                            else (desk.height - y_images[0].height - sum(y_steps) // len(y_steps))
            except:
                shift_y = 0

            if len(x_offsets) != 0:
                desk.paste(
                    x_images[0].convert("RGBA"),
                    (shift_x, shift_y),
                    mask=self.image_mask
                )
                for i, img in enumerate(x_images[1:]):
                    shift_x += x_offsets[i]
                    desk.paste(
                        img.convert("RGBA"),
                        (shift_x, shift_y),
                        mask=self.image_mask
                    )

            if len(y_offsets) != 0:
                desk.paste(
                    y_images[0].convert("RGBA"),
                    (shift_x, shift_y),
                    mask=self.image_mask
                )
                for i, img in enumerate(y_images[1:]):
                    shift_y += y_offsets[i]
                    desk.paste(
                        img.convert("RGBA"),
                        (shift_x, shift_y),
                        mask=self.image_mask
                    )

        if destination_offset[0] == 0:
            x_offsets.append(0)
            x_scores.append(0)

        if destination_offset[1] == 0:
            y_offsets.append(0)
            y_scores.append(0)

        return (sum(x_offsets), sum(x_scores) / len(x_scores)), (sum(y_offsets), sum(y_scores) / len(y_scores))


    def goto(self,
             destination: tuple[int, int]
             ) -> tuple[tuple[int, float], tuple[int, float]]:
        return self.move(destination_offset=destination)

    def calculate_map_size(self):
        x_images: list[Image.Image] = [get_image().convert("RGBA")]
        x_offset = 0

        steps = [
            (500, 2, -10, 10),
            (100, 4, -20, 20)
        ]

        steps = 0

        self.move((100, 0), (1, 0), (-20, 20))
        steps += 1
        x_images.append(get_image().convert("RGBA"))
        x_offset += 500
        img0 = apply_mask_make_transparent(np.array(x_images[-2], dtype=np.int32), self.mask)
        img1 = apply_mask_make_transparent(np.array(x_images[-1], dtype=np.int32), self.mask)

        while (res := np_absolute_distance_image_comparison(img0, img1))[0] > 1.0:
            steps += 1
            logger.log(INFO, f"Image comparison score: {res[0]:.4f}")
            self.move((100, 0), (1, 0), (-20, 20))
            x_images.append(get_image().convert("RGBA"))
            x_offset += 500
            img0 = apply_mask_make_transparent(np.array(x_images[-2], dtype=np.int32), self.mask)
            img1 = apply_mask_make_transparent(np.array(x_images[-1], dtype=np.int32), self.mask)

        print(x_offset)


class MotionModule:
    def __init__(self,
        ui_mask: Image.Image | np.array,
        swipe_calibrator: SwipeCalibrator
    ):
        match isinstance(ui_mask, Image.Image):
            case True: self.__ui_mask: np.ndarray = to_int32(ui_mask)
            case False: self.__ui_mask: np.ndarray = ui_mask
        self.desk = Image.new("RGBA", (self.__ui_mask.shape[0], self.__ui_mask.height), (0, 0, 0, 0))# Check if an image with dim(0, 0) can exist
        self.swipe_calibrator = swipe_calibrator

    # TODO: move then estimate movement, and recalculate next movements
    # TODO: merge images at correct angles/offset between them
    # TODO: keep track of where we are regarding an initial position
    # TODO: a function to reset the position
    # TODO: a function to check and explore the map boundaries
    # TODO: a function to define the motion area from the mask

    @staticmethod
    def __angle_to_offset(distance: float, angle: float):
        return np.cos(angle) * distance, np.sin(angle) * distance
    
    def __resize_canvas(self, desk: Image.Image, screen_size: tuple[int, int]):
    

    def move_with_angle(self, distance: float, angle: float):
        pass

    def move_with_offset(self, offset: tuple[int, int]):
        pass
    
    def move_with_time(self):
        pass
    
    def move_with_tap(self):
        pass
    
    def goto(self, destination: tuple[int, int]):
        pass

    

if __name__ == "__main__":
    from matplotlib import pyplot as plt
    md = OldMotionModule(
        image_mask=Image.open("resources/islandempire_mask_alpha.png"),
        screen_size=(1080, 2340)
    )
    desk = Image.new("RGBA", (3000, 3000), (255, 0, 0))
    # print(
    #     md.move(
    #         step_number = (12, 5),
    #         destination_offset= (1200, 500),
    #         desk = desk
    #     )
    # )
    print(md.calculate_map_size())
    plt.imshow(desk)
    plt.show()
