from AI.src.stuffMerger.enums import MotionType, Towards
from AI.src.stuffMerger.utils.image_processing_utility import *
from AI.src.stuffMerger.utils.pen_calibration import SwipeCalibrator
from AI.src.stuffMerger.utils.resources_utility import *

from AI.src.constants import  *

import os
from logging import INFO
import mahotas

import numpy as np
from PIL import ImageDraw, Image


class OldMotionModule:
    """
    Parameters:
        image_mask: PIL Image used as mask for the movement, should be RGBA with transparency where the map is to be ignored,
            ignored zones are feasible for movement.
        starting_positions: (x, y) starting position on the map [default is (0,0), Top left corner]
        screen_size: (width, height) size of the screen
        motion_type: type of motion to use (swipe, tap)
        motion_area: 🔴 **REQUIRED IF motion_type is SWIPE** ((left_x,top_y), (right_x,bottom_y)) area of the screen to use for the motion
        motion_options: 🔴 **REQUIRED IF motion_type is TAP** ((x,y), (x,y), (x,y), (x,y)) up, right, down, left positions for tap motion
    """
    # TODO: another possible motion type is TAP_AND_HOLD where times define how much we move in a specific direction
    # TODO: proper diagonal support
    def __init__(self,
                 image_mask: Image.Image,
                 screen_size: tuple[int, int],
                 starting_positions: tuple[int, int] | None = (0, 0),
                 motion_type: MotionType = MotionType.SWIPE,
                 motion_area: tuple[tuple[int, int], tuple[int, int]] | None = None,
                 motion_options: tuple[tuple[int, int], tuple[int, int], tuple[int, int], tuple[int, int]] | None = None
                 ):
        self.position: tuple[int, int] = starting_positions
        self.position_history: list[tuple[int, int]] = [self.position]
        self.image_mask: Image.Image = image_mask
        self.mask: np.ndarray = np.array(image_mask, dtype=np.int32)
        self.screen_size: tuple[int, int] = screen_size
        self.motion_type: MotionType = motion_type
        self.motion_area: tuple[tuple[int, int], tuple[int, int]] | None = motion_area
        self.motion_options: tuple[tuple[int, int], tuple[int, int], tuple[int, int], tuple[int, int]] | None = motion_options
        if self.motion_type == MotionType.SWIPE and self.motion_area is None:
            raise ValueError("motion_area must be defined when motion_type is SWIPE")
        elif self.motion_type == MotionType.TAP and self.motion_options is None:
            raise ValueError("motion_options must be defined when motion_type is TAP")


    def move(self,
             destination_offset: tuple[int, int],
             step_number: tuple[int, int] = (4, 4),
             check_range: tuple[int, int] = (-30, 30),
             check_frequency: int = 1,
             desk: Image.Image | None = None,
             desk_coordinates: tuple[int, int] | None = None
             ) -> tuple[tuple[int, float], tuple[int, float]]:
        """
        Parameters:
            destination_offset: (x, y) define where you want to go relative to the current position
            step_number: how many steps you want to take to get there (steps are done for x an y separately)
                if in TAP mode destination offset will be only used to define the actual position but will not be checked.
            check_range: range of offset to validate the location (a, b) a->b (a can be negative)
            check_frequency: how many pixels between each check (1 = every pixel)
            desk: the desk image generated by the movement, if not passed it will not be generated, if it is it will be overwritten
            desk_coordinates: (x, y) coordinates on the desk where to paste the movement images (referred to the top left
                corner of the screen) is not passed the borders of the desk will be used
        Returns:
            ((x_offset, x_error), (y_offset, y_error)) if in TAP mode the error will be 0 since no checking is done
        """
        #TODO: implement motion types
        if check_range[0] > check_range[1]:
            raise ValueError("check_range[0] must be lower than check_range[1]")

        x_offsets: list[int] = []
        x_scores: list[float] = []
        if destination_offset[0] != 0:
            x_steps = [destination_offset[0] // step_number[0] for _ in range(step_number[0])]
            x_orientation = Orientation.DESCENDING if destination_offset[0] > 0 else Orientation.ASCENDING  # Forse ho invertito descending e ascending
            if sum(x_steps) != destination_offset[0]:
                x_steps[-1] += destination_offset[0] - sum(x_steps)
            x_images: list[Image.Image] = [get_image().convert("RGBA")]

            for i in range(step_number[0]):
                #TODO: if we're not in the correct position we should recalculate the steps to try and get to the correct end position
                next_img = get_custom_image(
                    orientation=x_orientation,
                    direction=Direction.HORIZONTAL,
                    offset=x_steps[i],
                    name=f"x_{i}.png"
                ).convert("RGBA")
                best_shift, best_score = find_best_offset(
                    _img0=x_images[-1],
                    _img1=next_img,
                    _mask=self.mask,
                    base_shift=x_steps[i],
                    check_range=(check_range[0], check_range[1]),
                    check_step=check_frequency,
                    direction=Direction.HORIZONTAL,  # più che direction sarebbe verso
                    orientation=x_orientation
                )
                delta = best_shift + (-x_steps[i] if x_orientation == Orientation.DESCENDING else x_steps[i])
                logger.log(INFO, f"Best horizontal shift: {best_shift} px (delta vs STEP: {delta} px), score: {best_score:.4f}")
                x_offsets.append(best_shift)
                x_scores.append(best_score)
                self.position = (self.position[0] + best_shift, self.position[1])
                self.position_history.append(self.position)
                x_images.append(next_img)

        y_offsets: list[int] = []
        y_scores: list[float] = []
        if destination_offset[1] != 0:
            y_steps = [destination_offset[1] // step_number[1] for _ in range(step_number[1])]
            y_orientation = Orientation.DESCENDING if destination_offset[
                                                          1] > 0 else Orientation.ASCENDING  # Forse ho invertito descending e ascending
            if sum(y_steps) != destination_offset[1]:
                y_steps[-1] += destination_offset[1] - sum(y_steps)
            y_images: list[Image.Image] = [get_image().convert("RGBA")]

            for i in range(step_number[1]):
                next_img = get_custom_image(
                    orientation=y_orientation,
                    direction=Direction.VERTICAL,
                    offset=y_steps[i],
                    name=f"y_{i}.png"
                ).convert("RGBA")
                best_shift, best_score = find_best_offset(
                    _img0=y_images[-1],
                    _img1=next_img,
                    _mask=self.mask,
                    base_shift=y_steps[i],
                    check_range=(check_range[0], check_range[1]),
                    check_step=check_frequency,
                    direction=Direction.VERTICAL,  # più che direction sarebbe verso
                    orientation=y_orientation
                )
                delta = best_shift + (-y_steps[i] if y_orientation == Orientation.DESCENDING else y_steps[i])
                logger.log(INFO,
                           f"Best vertical shift: {best_shift} px (delta vs STEP: {delta} px), score: {best_score:.4f}")
                y_offsets.append(best_shift)
                y_scores.append(best_score)
                self.position = (self.position[0], self.position[1] + best_shift)
                self.position_history.append(self.position)
                y_images.append(next_img)

        # End Phase

        if desk is not None:
            try:
                shift_x = 0 if x_orientation == Orientation.DESCENDING \
                            else (desk.width - x_images[0].width - sum(x_steps) // len(x_steps))
            except:
                shift_x = 0

            try:
                shift_y = 0 if y_orientation == Orientation.DESCENDING \
                            else (desk.height - y_images[0].height - sum(y_steps) // len(y_steps))
            except:
                shift_y = 0

            if len(x_offsets) != 0:
                desk.paste(
                    x_images[0].convert("RGBA"),
                    (shift_x, shift_y),
                    mask=self.image_mask
                )
                for i, img in enumerate(x_images[1:]):
                    shift_x += x_offsets[i]
                    desk.paste(
                        img.convert("RGBA"),
                        (shift_x, shift_y),
                        mask=self.image_mask
                    )

            if len(y_offsets) != 0:
                desk.paste(
                    y_images[0].convert("RGBA"),
                    (shift_x, shift_y),
                    mask=self.image_mask
                )
                for i, img in enumerate(y_images[1:]):
                    shift_y += y_offsets[i]
                    desk.paste(
                        img.convert("RGBA"),
                        (shift_x, shift_y),
                        mask=self.image_mask
                    )

        if destination_offset[0] == 0:
            x_offsets.append(0)
            x_scores.append(0)

        if destination_offset[1] == 0:
            y_offsets.append(0)
            y_scores.append(0)

        return (sum(x_offsets), sum(x_scores) / len(x_scores)), (sum(y_offsets), sum(y_scores) / len(y_scores))


    def goto(self,
             destination: tuple[int, int]
             ) -> tuple[tuple[int, float], tuple[int, float]]:
        return self.move(destination_offset=destination)

    def calculate_map_size(self):
        x_images: list[Image.Image] = [get_image().convert("RGBA")]
        x_offset = 0

        steps = [
            (500, 2, -10, 10),
            (100, 4, -20, 20)
        ]

        steps = 0

        self.move((100, 0), (1, 0), (-20, 20))
        steps += 1
        x_images.append(get_image().convert("RGBA"))
        x_offset += 500
        img0 = apply_mask_make_transparent(np.array(x_images[-2], dtype=np.int32), self.mask)
        img1 = apply_mask_make_transparent(np.array(x_images[-1], dtype=np.int32), self.mask)

        while (res := np_absolute_distance_image_comparison(img0, img1))[0] > 1.0:
            steps += 1
            logger.log(INFO, f"Image comparison score: {res[0]:.4f}")
            self.move((100, 0), (1, 0), (-20, 20))
            x_images.append(get_image().convert("RGBA"))
            x_offset += 500
            img0 = apply_mask_make_transparent(np.array(x_images[-2], dtype=np.int32), self.mask)
            img1 = apply_mask_make_transparent(np.array(x_images[-1], dtype=np.int32), self.mask)

        logger.debug(x_offset)

class MotionModule:
    def __init__(self,
        ui_mask: Image.Image | np.ndarray,
        swipe_calibrator: SwipeCalibrator,
        motion_type: MotionType = MotionType.SWIPE,
        image_history_size: int = 10
    ):
        """
        Parameters:
            ui_mask: an image or a ndArray representing the mask of the UI you want to interact with.
            swipe_calibrator: Used to correct some error of the pointing device, you can omit it.
                The swipe calibrator (if provided) need to be already trained.
            motion_type: the type of motion you want to use, default is swipe.
        """
        match isinstance(ui_mask, Image.Image):
            case True: self._ui_mask: np.ndarray = to_int32(ui_mask)
            case False: self._ui_mask: np.ndarray = ui_mask
        height, width = self._ui_mask.shape[:2]
        # array RGBA trasparente (0 = trasparente)
        self.desk = np.zeros((height, width, 4), dtype=np.uint8)
        self.desk_offset = (0, 0)
        self.swipe_calibrator = swipe_calibrator
        self._position: tuple[int, int] = (0, 0)
        self._positions_history: list[tuple[int, int]] = []
        self._frames_history: list[np.ndarray] = []
        self._frame_history_size: int = image_history_size
        self._motion_type: MotionType = motion_type
        self._motion_area: tuple[tuple[int, int], tuple[int, int]] | None = None
        if motion_type == MotionType.SWIPE:
            self.calculate_motion_area()

    # TODO: add a way to auto-train the swipe calibrator
    # TODO: add confidence threshold to have some kind of security net for wrong movement, and a correction for them
    # TODO: move then estimate movement, and recalculate next movements
    # TODO: merge images at correct angles/offset between them
    # TODO: keep track of where we are regarding an initial position
    # TODO: a function to reset the position
    # TODO: a function to check and explore the map boundaries
    # TODO: a function to define the motion area from the mask

    @staticmethod
    def angle_to_offset(distance: float, angle: float):
        return np.cos(angle) * distance, np.sin(angle) * distance
    
    def _expand_desk(self, x: int, y: int, width: int, height: int):
        current_x, current_y = self.desk_offset
        desk_h, desk_w = self.desk.shape[:2]

        min_x = min(current_x, x)
        min_y = min(current_y, y)
        max_x = max(current_x + desk_w, x + width)
        max_y = max(current_y + desk_h, y + height)

        if min_x < current_x or min_y < current_y or max_x > current_x + desk_w or max_y > current_y + desk_h:
            new_w = max_x - min_x
            new_h = max_y - min_y
            new_desk = np.zeros((new_h, new_w, 4), dtype=np.uint8)

            offset_x = current_x - min_x
            offset_y = current_y - min_y

            new_desk[offset_y:offset_y + desk_h, offset_x:offset_x + desk_w] = self.desk
            self.desk = new_desk
            self.desk_offset = (min_x, min_y)

    def _add_frame_to_desk(self, frame: np.ndarray, coordinates: tuple[int, int]):
        masked_frame = apply_mask_make_transparent(frame, self._ui_mask).astype(np.uint8)
        h, w = masked_frame.shape[:2]
        x, y = coordinates

        self._expand_desk(x, y, w, h)

        desk_x = x - self.desk_offset[0]
        desk_y = y - self.desk_offset[1]

        mask = masked_frame[:, :, 3] > 0
        self.desk[desk_y:desk_y + h, desk_x:desk_x + w][mask] = masked_frame[mask]
    
    def _add_last_frame_to_desk(self):
        self._add_frame_to_desk(self._frames_history[-1], coordinates=self._position)

    def _calculate_offset(self) -> tuple[float, float, float]:
        """
        Calculates the offset between the last two frames in the history, using the UI mask to ignore irrelevant areas.
        """
        # Image.fromarray(self._frames_history[-2]).save("saved0.png")
        # Image.fromarray(self._frames_history[-1]).save("saved1.png")
        dx, dy, confidence = calculate_offset(
            self._frames_history[-2],
            self._frames_history[-1],
            self._ui_mask,
            1
        )
        logger.debug(f"dx = {dx}, dy = {dy}, confidence = {confidence}")
        return dx, dy, confidence
    
    def calculate_motion_area(self, borders: int = 10):
        """
        Parameters:
            borders: the distance we want to maintain from the border of the mask
        https://www.geeksforgeeks.org/dsa/largest-rectangular-area-in-a-histogram-using-stack/
        """
        
        # Could be made protected/private
        # TODO: Optimize the motion area for vertical and horizontal movement

        if self._ui_mask.ndim == 3:
            binary_mask = self._ui_mask[:, :, 3] != 0
        else:
            binary_mask = self._ui_mask != 0

        distance_map = mahotas.distance(binary_mask)
        valid_region = distance_map > borders

        rows, cols = valid_region.shape
        heights = np.zeros(cols, dtype=np.int32)
        max_area = 0
        best_rect = ((0, 0), (0, 0))

        for r in range(rows):
            heights = np.where(valid_region[r], heights + 1, 0)
            stack = [-1]
            for c in range(cols + 1):
                h = heights[c] if c < cols else 0
                while stack[-1] != -1 and heights[stack[-1]] >= h:
                    height = heights[stack.pop()]
                    width = c - stack[-1] - 1
                    area = height * width
                    if area > max_area:
                        max_area = area
                        best_rect = ((stack[-1] + 1, r - height + 1), (c, r + 1))
                stack.append(c)

        self._motion_area = best_rect

    def offset_to_swipe(self, offset: tuple[int, int]) -> tuple[int, int, int, int] | None:
        """
        Converts a desired offset into swipe coordinates based on the motion area.
        Parameters:
            offset: the desired offset, in pixels (x, y).
        Returns:
            start_x, start_y, end_x, end_y || None if the offset is out of bounds.
        """
        if self._motion_area is None:
            self.calculate_motion_area()

        (min_x, min_y), (max_x, max_y) = self._motion_area

        area_width = max_x - min_x
        area_height = max_y - min_y

        target_x, target_y = offset

        if abs(target_x) > area_width or abs(target_y) > area_height:
            logger.info(f"Desired offset {offset} is out of bounds for the motion area.")
            return None

        # Center the swipe vector in the available space (kinda works)
        # start_x = (min_x + max_x - target_x) // 2 # <- +x ; -> -x
        start_x = (min_x + max_x + target_x) // 2 # <- -x ; -> +x
        start_y = (min_y + max_y - target_y) // 2

        # end_x = start_x + target_x # <- +x ; -> -x
        end_x = start_x - target_x # <- -x ; -> +x
        end_y = start_y + target_y

        return int(start_x), int(start_y), int(end_x), int(end_y)
    
    @staticmethod
    def _swipe(start_x: int, start_y: int, end_x: int, end_y: int):
        old_directory: str = os.getcwd()
        os.chdir(CLIENT_PATH)
        os.system(f"python3 client3.py --url {TAPPY_ORIGINAL_SERVER_PROTOCOL}://{TAPPY_ORIGINAL_SERVER_IP}:{TAPPY_ORIGINAL_SERVER_PORT} --light 'swipe {start_x} {start_y} {end_x} {end_y}'")
        os.chdir(old_directory)

    def _clamp_frame_history(self, keep: int = None):
        if keep is None: keep = self._frame_history_size
        self._frames_history = self._frames_history[-keep:]

    def _ensure_history(self):
        """
        Make sure there are at least one frame in the history, so we can calculate the offset.
        """
        if len(self._frames_history) < 2:
            self._positions_history.append(self._position)
            self._frames_history.append(run_adb_screencap_to_memory(save_file = f"test_{len(self._frames_history)}.png"))

    @staticmethod
    def distance(point_a: tuple[int, int], point_b: tuple[int, int]) -> float:
        return ((point_a[0] - point_b[0]) ** 2 + (point_a[1] - point_b[1]) ** 2) ** 0.5

    def move_with_offset(self, offset: tuple[int, int]) -> tuple[float, float] | None:
        """
        Tries to move the map ONCE by swiping
        Parameters:
            offset: int(x), int(y), how much you want to move, DO NOT pre-calibrate these values
        Returns:
            offset_x, offset_y || None if something went wrong
        """    
        self._ensure_history()
        command = self.swipe_calibrator.get_calibrated_command(*offset)
        command = int(command[0]), int(command[1])
        swipe = self.offset_to_swipe(command)
        if swipe is None:
            #Note: here you should NOT retry with multiple swipes command, the move command should only do ONE action
            return None
        self._swipe(*swipe)
        
        self._frames_history.append(run_adb_screencap_to_memory(save_file = f"test_{len(self._frames_history)}.png"))
        dx, dy, confidence = self._calculate_offset()
        self._position = (self._position[0] - int(dx), self._position[1] - int(dy))
        self._positions_history.append(self._position)
        self._add_last_frame_to_desk()
        self._clamp_frame_history()
        
        return dx, dy
        
    def move_with_angle(self, distance: float, angle: float) -> tuple[float, float] | None:
        """
        Tries to move the map ONCE by swiping
        Parameters:
            distance: how far you want to move, in pixels
            angle: the angle you want to move, in radians
        Returns:
            offset_x, offset_y: None if something went wrong
        """
        self._ensure_history()
        # TODO: may need to invert (*-1) angle_to_offset result to have it match the screen coordinates
        pass
    
    def move_with_time(self):
        """
        Tries to move the map ONCE by pressing for x time on a point
        """
        self._ensure_history()
        # TODO: to implement
        """
        The problem with this function is the press may become faster exponentially and cap at some point
        We need to have an approximation of fun(time) = movement
        So another calibration step
        """
        pass
    
    def move_with_tap(self, towards: Towards):
        """
        Tries to move the map ONCE by tapping on a point
        Parameters:
            The direction we want to move to
        Returns:
            ???
        """
        #TODO: to implement
        """
        The problem with this function is that a tap may move a fixes amount or a full screen
        it need to be set prior to moving and for each game
        """
        pass
    
    def goto(self, destination: tuple[int, int], acceptable_distance: float = 50):
        """
        Goes to an absolute destination
        Parameters:
            destination: the absolute destination, in pixels (x, y)
            acceptable_distance: the maximum distance from the destination we are willing to accept
        Returns:
            The final absolute position (x,y)
        """
        
        if self._motion_area is None:
            # It's redundant, but I feel safer
            self.calculate_motion_area()
        
        # min-max
        max_x_movement = abs(self._motion_area[0][0] - self._motion_area[1][0])
        max_y_movement = abs(self._motion_area[0][1] - self._motion_area[1][1])
        
        #TODO: if we fails to move 2/3 times return the current position and stop
        
        while (dist := self.distance(self._position, destination)) > acceptable_distance:
            logger.debug(f"Distance to destination: {dist}")

            x_distance = destination[0] - self._position[0]
            y_distance = destination[1] - self._position[1]
            
            clamped_x = int(max(-(max_x_movement//2), min((max_x_movement//2), x_distance)))
            clamped_y = int(max(-(max_y_movement//2), min((max_y_movement//2), y_distance)))
            
            movement = (clamped_x, clamped_y)
            
            self.move_with_offset(movement)

        return self._position
    
    def get_pil_desk(self) -> Image.Image:
        return Image.fromarray(self.desk, mode="RGBA")

    def position(self):
        return self._position

class TestMotionModule(MotionModule):
    def test_draw_largest_bbox(self, output_path: str = "bbox_output.png"):
        """
            you will never guess what this does
        """
        self.calculate_motion_area()
        if self._motion_area is not None:
            (x1, y1), (x2, y2) = self._motion_area
            logger.debug(f"Bounding Box found: {self._motion_area}")
            img = Image.fromarray(self._ui_mask.astype(np.uint8))
            draw = ImageDraw.Draw(img)
            draw.rectangle([x1, y1, x2 - 1, y2 - 1], fill="green", outline="red", width=5)
            img.save(output_path)
            logger.debug(f"Image saved to {output_path}")
        else:
            logger.debug("No bounding box calculated.")


if __name__ == "__main__":
    logger.debug(os.getcwd())
    
    cal = SwipeCalibrator()
    cal.load()
    cal.train()
    # cal.plot_calibration()
    
    motion_module = MotionModule(
        ui_mask=Image.open("../resources/p10lite/islandempire_mask_alpha.png").convert("RGBA"),
        swipe_calibrator=cal
    )
    # motion_module.move_with_offset((300,0))
    # motion_module.move_with_offset((300,0))
    # motion_module.move_with_offset((300,0))
    motion_module.goto((900,0))
    # motion_module.move_with_offset((-200,0))
    # motion_module.move_with_offset((0,200))
    # motion_module.move_with_offset((0,-200))
    print(motion_module.position())
    Image.fromarray(motion_module.desk).save("desk2.png")
    # motion_module.test_draw_largest_bbox()
    
    # from matplotlib import pyplot as plt
    # md = OldMotionModule(
    #     image_mask=Image.open("resources/islandempire_mask_alpha.png"),
    #     screen_size=(1080, 2340)
    # )
    # desk = Image.new("RGBA", (3000, 3000), (255, 0, 0))
    # # logger.debug(
    # #     md.move(
    # #         step_number = (12, 5),
    # #         destination_offset= (1200, 500),
    # #         desk = desk
    # #     )
    # # )
    # # )
    # logger.debug(md.calculate_map_size())
    # plt.imshow(desk)
    # plt.show()
